# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linux test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  etapa1:

    runs-on: ubuntu-latest
    defaults:

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install build-essential -y
    - name: Test Linux script
      run: make test